justjavac/awesome-wechat-weapp

README.md

增加开源项目： weapp-gold

---

README.md

add wechat-v2ex demo

---

README.md

add wechat-app-zhihudaily

---

README.md

原文里的2048小游戏并没有实现，我提交的版本已经实现了2048的功能

原文里的2048小游戏并没有实现，我提交的版本已经实现了2048的功能

---

README.md

HiApp 是一个类似于微博的社交软件的开源版
wxapp-hiapp 为微信小程序的实现

新增 wxapp-hiapp

---

README.md

微信小程序要这样解读：http://blog.csdn.net/yanzhenjie1003/article/details/52698184。

Add link for article section.

---

README.md

Egret Wing 3.2.x 支持微信小程序的创建项目，代码提示，对当前wxml的页面的实时预览。 功能参考：
http://developer.egret.com/cn/github/egret-docs/Wing/update/update320/index.html

Egret Wing 3.2.x 

---

README.md

add layout example fix conflict

---

README.md

播放器调用 百度音乐api 
已实现：
- 各种榜单歌曲列表展示
- 在线搜索
- 列表无限加载
- 后台播放音乐

添加 音乐播放器 小程序demo

---

README.md

添加微信小程序-简易计算器

---

README.md

更加优雅的方式实现微信小程序2048，原rep中的程序还有很大的改进空间

更新2048游戏的实现

---

README.md

微信小程序之小熊の日记

---

README.md

Add a boilerplate application

---

README.md

增加微信小程序 - Artand

---

README.md

添加基于微信小程序的UI库

---

README.md

hi, I wrote a simple wechat app which is a photo grid or fullscreen browser base on Node.js server, they are both in my repository which contains two photo resource: douban.com girls group & meizitu.com. [more detail](https://github.com/litt1e-p/weapp-girls). may I make this PR? thanks for your great repo

douban girls & meizitu girls photo browser via node.js scrapy & wechat app 

---

README.md

添加新的微信小程序--仿知乎代码例子

---

README.md

加入官方宣布公测的重要时间点新闻

---

README.md

添加了国内一些讨论的社区。

---

README.md

Add WeApp-Demo

---

README.md

add new case

---

README.md

加入一个小程序Demo。

---

README.md

- 添加轮子 weapp-polyfill
- 添加 Demo LeanTodo

添加 weapp-polyfill 与 LeanTodo

---

README.md

增加wxParse-微信小程序富文本解析自定义组件，支持HTML及markdown解析

增加wxParse-微信小程序富文本解析自定义组件，支持HTML及markdown解析

---

README.md

通过github ID 来生成对应的简历，受到 http://resume.github.io/ 的启发

添加一个小程序例子 github简历

---

README.md

云端组件清单 :
用户 User
会话 Session
信道 Wss
支付 Pay
云端数据表 Table
本地存储加强 Stor

+ 微信小程序云端 SDK -XpmJS

---

README.md

wx-drawer模仿QQ6.0侧滑菜单

---

README.md

Add douban-movie and douban-location demo.

---

README.md

增加gulp-wxa-copy-npm的连接

---

README.md

1.增加- - [微信小程序垂直开发社区](https://weappdev.com/)

1.增加- - [微信小程序垂直开发社区](https://weappdev.com/)

---

README.md

增添 煎蛋微信小程序

---

README.md

微信小程序请求并发数超过 10 个后，小程序直接就不发起请求了，所以写了一个管理请求队列的库 wx-promise-request 来帮助大家解决该问题。

增加请求队列管理库 wx-promise-request

---

README.md

Add a gulp workflow and some articles.

---

README.md

WePY第三方组件汇总pr

---

README.md

[Chg] 添加 wxDraw 小程序canvas动画库,让小程序canvas支持动画和交互事件

[Chg] 添加 wxDraw 小程序canvas动画库,让小程序canvas支持动画和交互事件

---

README.md

https://github.com/haojy/weact
https://www.npmjs.com/package/weact-cli

添加工具 weact

---

README.md

微信小程序 - 滑块拼图

---

README.md

添加 Tina.js

---

README.md

基于EgretEngine开发的游戏框架，游戏小程序需升级至5.1.X。

自荐自己长期维护的游戏小程序框架

---

README.md

之前项目有变动，修改一下文档；添加 weapp-start；欢迎 pr～

weappx & weapp-start

---

README.md

add tools wxapp-graphql

---

README.md

增加一个好用的微信小程序自动化测试框架Airtest的使用教程

增加Airtest测试框架

---

README.md

加入一个新的Demomo

---

README.md

在README.md中增加一个全面支持WePY开发的PhpStorm/WebStorm插件。[插件地址](http://wepy.iniself.com)

Add one PhpStorm/WebStorm Plugin

---

README.md

minapp 中提供了不少小程序开发工具
- 有 wx api 自动补全的 wx.d.ts 描述文件
- 有功能非常强大的 vscode 插件
- 还有个开发小程序的框架
- ...  
https://github.com/qiu8310/minapp

添加 minapp 相关资源

---

README.md

微信小程序上canvas绘制图片助手，一个json就制作分享朋友圈图片

增加 mp_canvas_drawer 组件

---

README.md

增加小程序demo口袋吉他

---

README.md

 增加gulp-wxapp-boilerplate项目

---

README.md

添加 weapp-cookie 组件

---

README.md

微信小程序Canvas手写板(可用于采集用户签名，笔画自然，自定义颜色，笔画粗细)

微信小程序Canvas手写板

---

README.md

Add: 滴滴跨端解决方案 - chameleon框架

---

README.md

Add mpvue-calendar component.

---

README.md

Add：全球主要城市地铁线路图小程序

---

README.md

之前mpvue已经超过半年没重大更新了，megalo可以作为一个替代方案

Add: 网易解决方案 - megalo框架

---

README.md

为微信小程序提供的网络请求组件，是 wx.request 的扩展，基于 Promise API，添加缓存控制

Add: 网络请求组件 weapp.request

---

README.md

Add:微信智能小管家 (使用微信小程序控制你的硬件设备)

---

README.md

新增iw3cplus小程序

---

README.md

相关文章：[Licia 支持小程序的 JS 工具库](https://juejin.im/post/5ccece5d51882540e974b4c5)

Add: 支持小程序的 JS 工具库 Licia

---

README.md

文档官网：https://didi.github.io/mpx/

Add: 增强型小程序框架MPX

---

README.md

开发了一个下拉上拉刷新组件，开源出来大家一起用
https://github.com/zhongxuqi/wx-pulltorefresh-view

开发了一个下拉上拉刷新组件，开源出来大家一起用

---

README.md

修改了官网开放文档链接，原链接失效，并更新了几个框架star数量

修改了官网开放文档链接

---

README.md

Reverts justjavac/awesome-wechat-weapp#255

Revert "Update weapp-monument-valley to 100+"

---

README.md

update weapp-monument-valley to 100+

update weapp-monument-valley to 100+

---

README.md

增加微信开发者工具的wxml、wxs、wxss文件编译器的nodejs实现

feat: add wcc.js adn wcsc.js

---

README.md

将失效项目移除，替换为自己的项目作品

---

README.md

推荐Gulp高效构建微信小程序，让开发变得更简单

---

README.md

vscode-live-sass-compiler插件根据.scss文件自动生成wxss文件

vscode-live-sass-compiler插件根据.scss文件自动生成wxss文件

---

README.md

https://github.com/BranLiang/game-stop-app

Add demo app PSN降价了

---

README.md

修改sol-weapp组件github地址

---

README.md

[wx-updata](https://github.com/SHERlocked93/wx-updata) 微信小程序官方 setData 最佳替代品，只修改 data 中你希望修改的部分 ✈️
教程地址：[开发微信小程序，我为什么放弃 setData，使用 upData](https://juejin.im/post/5f17efb55188252e7811dcdd#comment)
小程序代码片段预览地址： [developers.weixin.qq.com/s/CcXdO1mc73jD](https://developers.weixin.qq.com/s/CcXdO1mc73jD)
小程序代码片段代码地址： [SHERlocked93/wx\-updata\-demo](https://github.com/SHERlocked93/wx-updata-demo)

feat: 增加 wx-updata 组件

---

README.md

文档齐全，含部署说明，UI使用sketch设计，源码开源，文件开源。
云开发实现 好友对战、随机匹配、人机对战
https://github.com/arleyGuoLei/wx-words-pk

Add demo: 单词天天斗, 云开发单词对战小程序

---

README.md

我在测试这些项目时发现很多程序的后端接口有问题，无法成功运行起来，所以希望能把这些项目分为两类，让浏览者可以更块的找到自己需要的项目

将Demo分为两类，一类是数据接口没问题，可以直接运行，一类是有问题的

---

README.md

feat: add mp-html component

---

README.md

新增腾讯云开发部署工具 CloudBase Framework
官方提供的小程序云开发部署工具

新增腾讯云开发部署工具 CloudBase Framework

---

README.md

添加vue-custom-hooks、image-cropper

1977474741 patch 1

---

README.md

Add appDemo focus-clock

---

README.md

根据最新版`Windows`版开发工具移植的`Linux`下的开发工具

add msojocs/wechat-web-devtools-linux

---

README.md

增加小程序app demo

---

README.md

添加 weapp-tailwindcss-webpack-plugin 插件链接
